import org.junit.Test;
import static org.junit.Assert.*;


/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'zflavia' at '7/20/17 11:56 AM' with Gradle 2.12
 *
 * @author zflavia, @date 7/20/17 11:56 AM
 */

public class LibraryTest {
    /*@Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }*/
}
